##Data enrichment & final cleaning
CREATE OR REPLACE TABLE deft-stratum-473608-d1.free2move_test.free2move_cleaned AS (
SELECT 
  VEHICLE_ID, 
  MODEL_ID,
  STARTED_TIME,
  FINISHED_TIME,
  DURATION, 
  ROUND(DURATION_MIN,2) AS DURATION_MIN, 
  CHARGELEVELSTART,
  CASE
    WHEN CHARGELEVELSTART < 10 THEN '0-10'
    WHEN CHARGELEVELSTART < 20 THEN '10-20'
    WHEN CHARGELEVELSTART < 30 THEN '20-30'
    WHEN CHARGELEVELSTART < 40 THEN '30-40'
    WHEN CHARGELEVELSTART < 50 THEN '40-50'
    WHEN CHARGELEVELSTART < 60 THEN '50-60'
    WHEN CHARGELEVELSTART < 70 THEN '60-70'
    WHEN CHARGELEVELSTART < 80 THEN '70-80'
    WHEN CHARGELEVELSTART < 90 THEN '80-90'
    WHEN CHARGELEVELSTART <= 100 THEN '90-100'
    ELSE 'previous endlevel'
  END AS BATTERY_LEVEL_START,
  CHARGELEVELEND,
  CASE 
    WHEN CHARGELEVELEND < 10 THEN '0-10'
    WHEN CHARGELEVELEND < 20 THEN '10-20'
    WHEN CHARGELEVELEND < 30 THEN '20-30'
    WHEN CHARGELEVELEND < 40 THEN '30-40'
    WHEN CHARGELEVELEND < 50 THEN '40-50'
    WHEN CHARGELEVELEND < 60 THEN '50-60'
    WHEN CHARGELEVELEND < 70 THEN '60-70'
    WHEN CHARGELEVELEND < 80 THEN '70-80'
    WHEN CHARGELEVELEND < 90 THEN '80-90'
    WHEN CHARGELEVELEND <= 100 THEN '90-100'
    ELSE NULL
  END AS BATTERY_LEVEL_END,
  CAST(CHARGED AS INT64) AS CHARGED,
  CAST(SERVICERENTAL AS INT64) AS SERVICERENTAL
FROM `deft-stratum-473608-d1.free2move_test.free2move_cleaned` 
WHERE DURATION_MIN > 0
ORDER BY VEHICLE_ID ASC, STARTED_TIME ASC);

##Analysing events on one car (no table created)
SELECT * 
FROM `deft-stratum-473608-d1.free2move_test.free2move_cleaned` 
WHERE VEHICLE_ID = '0592a3e4a455ba32227b24f88215cce6'
ORDER BY STARTED_TIME ASC;


CREATE OR REPLACE TABLE deft-stratum-473608-d1.free2move_test.customer_rentals AS (
  SELECT 
    VEHICLE_ID,
    MODEL_ID,
    STARTED_TIME,
    FINISHED_TIME,
    DURATION,
    DURATION_MIN,
    CHARGELEVELSTART,
    BATTERY_LEVEL_START,
    CHARGELEVELEND,
    BATTERY_LEVEL_END,
    CHARGED,
  FROM `deft-stratum-473608-d1.free2move_test.free2move_cleaned` 
  WHERE SERVICERENTAL = 0
)

SELECT * FROM deft-stratum-473608-d1.free2move_test.free2move_cleaned;